### ISSUE TITLE
Blocklist Limitations and Removal

### ISSUE THREAD

**Issue by Timbone1343** [hollabee/deeperblacklist#4]
I know this is not within your power, but it should be noted that once you upload this you cannot mass remove it. 

You have to remove them 10 at a time because the UI will not load more than that.

Also, the blocklist in AtomOS appears to be limited to 100 pages which is 1000 entries, meaning that the lower 95+% of the list is not even blocked.

OR 

It's possible that even though the block list only shows 1000 entries it will still allow more to be entered via upload. Although if this is the case that now means you can never remove those domains from the blocklist so if you run into a false positive then you're just screwed.

Bad news either way.

**Comment by hollabee** [comment]
We realized that there is a limitation in the current Firmware 1.1.14.rel. We will get in touch with the Deeper developers, but cannot promise anything.

You are absolutely right, currently, you can only remove items on the list in batches of 10 (even if the selection is made to show 100 entries, it does not work). We will also address this.
